### ISSUE TITLE
🐞: No text showing up in window

### ISSUE THREAD

**Issue by markbattistella** [lukepistrol/TimeMachineStatus#11]
**Describe the bug**
No progress text (like the images) when performing a backup.

**To Reproduce**
1. Go to app
2. Click on "Play" button

**Expected behavior**
To see something like this:

![image](https://github.com/lukepistrol/TimeMachineStatus/assets/17962160/fc4fe1c9-83db-444d-83e8-012aa83a3cbc)

**Screenshots**

https://github.com/lukepistrol/TimeMachineStatus/assets/17962160/c984ed39-69c1-4ec2-9b05-0a6e79199117

**Additional context**
- Two different TM drives, only one connected a time (on-site / off-site)
- M2 Sonoma 14.0
- Full disk access is permitted, app rebooted, system rebooted

**Comment by lukepistrol** [comment]
Thanks for your report! This might be a problem because of the way apple encodes the volume info. This unfortunately is not documented very well and there might be some unexpected data points or data points missing in your specific configuration.

To fix this I need a bit more information.

Please open your `Terminal.app` and type in the following command to save the logs to a file on your Desktop. Ideally right after you restarted the app. Make sure to change the time stamp to before the error occurred.

```sh
log show --predicate 'sender == "TimeMachineStatus"' --start '2023-11-15 00:05:00' > ~/Desktop/TMS.log
```

Then please attach the file here.

Thanks again for your report! 😊

**Comment by markbattistella** [comment]
No issue - happy to help on such a nice app.

The repeated error is:

`2023-11-15 10:26:01.838501+1100 0x9697     Error       0x0                  2051   0    TimeMachineStatus: [com.lukaspistrol.TimeMachineStatus.TMUtility:] Error reading preferences: keyNotFound(CodingKeys(stringValue: "ExcludedVolumeUUIDs", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"ExcludedVolumeUUIDs\", intValue: nil) (\"ExcludedVolumeUUIDs\").", underlyingError: nil))`


[TMS.log](https://github.com/lukepistrol/TimeMachineStatus/files/13358254/TMS.log)

**Comment by lukepistrol** [comment]
Can you please check whether this is fixed in version 0.0.3? You can just update from within the app:

![Screenshot 2023-11-14 at 03 20 01](https://github.com/lukepistrol/TimeMachineStatus/assets/9460130/1f39a06d-27f3-48bc-866a-e6a962cbfa11)

**Comment by markbattistella** [comment]
There is a visible error message now, but still no UI for progress:

![image](https://github.com/lukepistrol/TimeMachineStatus/assets/17962160/87ed9630-8eaa-4461-9b15-36b78de185c9)

My drives are encrypted though - so I wonder too if that is an edge case?

**Comment by lukepistrol** [comment]
Ok, could you send me the logs once again please?

**Comment by markbattistella** [comment]
Seems to be working in 0.0.6!

![Screenshot 2023-11-16 at 4 17 14 pm](https://github.com/lukepistrol/TimeMachineStatus/assets/17962160/189b34fe-2109-4427-a5df-980c0e6c0878)
