### ISSUE TITLE
🐞: Menubar item window opens beyond screen edge

### ISSUE THREAD

**Issue by MrKai77** [lukepistrol/TimeMachineStatus#12]
**Describe the bug**

Thank you for this amazing app!
The menubar item dropdown window opens beyond screen edge.

**To Reproduce**

1. Move menubar item to end of menubar (you may need to set the system clock to the analog one)
2. Open the menubar item

**Expected behavior**

Menubar item takes screen bounds into consideration and displaces dropdown window accordingly

**Screenshots**

<img width="456" alt="SCR-20231115-rvlp" src="https://github.com/lukepistrol/TimeMachineStatus/assets/68963405/5f81ca69-ea2a-42d3-aaa2-af49e95cccfd">

**Additional context**

**Comment by lukepistrol** [comment]
Should be fixed in `0.0.7`.
