### ISSUE TITLE
✨: macOS 13 Ventura support

### ISSUE THREAD

**Issue by huyz** [lukepistrol/TimeMachineStatus#13]
**What would you like to see added?**
Support for macOS 13 Ventura.  I'm not ready to go to macOS 14 and have a bunch of apps break, just yet.

**Comment by lukepistrol** [comment]
I'm sorry but due to this being a brand new app, I want to keep tech-debt low by allowing me to use latest API's, etc., and thus I'm only supporting Sonoma 14.0+ at this time.
