### ISSUE TITLE
🐞: [BUG] App is terminating itself ...

### ISSUE THREAD

**Issue by cpohli** [lukepistrol/TimeMachineStatus#23]
**Describe the bug**
The App is terminating itself after variing amounts of time.

**To Reproduce**

**Expected behavior**
Dont quit the App until i say so. :-)

**Screenshots**

**Additional context**
After a variing amount of time the app seems to terminat itself. I'm starting it as normal, see ist status in the menu bar and all seems fine. Every now and then (from mere seconds to hours) i com back to my mac and find the app terminated.

Mac Mini M1, Sonoma 14.2.1

**Comment by Bergruebe** [comment]
I have the same problem on Sonoma 14.4.1 with TimeMachineStatus 0.1.0

**Comment by cpohli** [comment]
I think i cann add that the self termination is happening right after a time machine backup is completed.
Perhaps that helps in some way ...

**Comment by lukepistrol** [comment]
Could anyone experiencing this issue provide some logs? This would be very helpful!

Please open your Terminal.app and type in the following command to save the logs to a file on your Desktop. Ideally right after you restarted the app. Make sure to change the time stamp to before the error occurred.

```
log show --predicate 'sender == "TimeMachineStatus"' --start '2023-11-15 00:05:00' > ~/Desktop/TMS.log
```

Then please attach the file here.

**Comment by cpohli** [comment]
Does not seem to happen anymore. I can not pinpoint a reason for that to be honest.
Just seems to work as intended atm. :-)
