### ISSUE TITLE
🐞: Typo in in status: "Next automatic backup in in 11h"

### ISSUE THREAD

**Issue by blackketter** [lukepistrol/TimeMachineStatus#25]
**Describe the bug**
There's a minor typo in the bottom status row of text, with the word "in" doubled, e.g. "Next automatic backup in in 11h"

**Screenshots**
<img width="226" alt="Untitled" src="https://github.com/lukepistrol/TimeMachineStatus/assets/131679/8dfebeb2-635e-4a8d-b1fa-ad8fd0ab01a1">

**Comment by lukepistrol** [comment]
Thanks for reporting this :)

**Comment by lukepistrol** [comment]
fix available in release 0.0.13
