### ISSUE TITLE
Draggable window

### ISSUE THREAD

**Issue by blackketter** [lukepistrol/TimeMachineStatus#26]
I just had the impulse to drag the TimeMachineStatus menu window to another part of my screen to keep it open to have an eye on the backup progress.  Not sure if this is a difficult thing to accomplish, but would be a nice little accommodation.  

Fantasical does this, as an example. 

Thanks!

**Comment by lukepistrol** [comment]
Thanks for submitting this request! I think this is a great idea. I'll have a look at it tomorrow if I get to it :)

**Comment by lukepistrol** [comment]
Implemented in Version [0.1.0](https://github.com/lukepistrol/TimeMachineStatus/releases/tag/0.1.0)

**Comment by blackketter** [comment]
Fantastic!  Works like a charm.  Thanks!
