### ISSUE TITLE
🐞: [BUG] Percentage unmatched

### ISSUE THREAD

**Issue by yamacin** [lukepistrol/TimeMachineStatus#29]
![screen](https://github.com/lukepistrol/TimeMachineStatus/assets/169577623/371a1b3e-c80b-472c-8c0e-5b5d53ea8bee)

**Comment by lukepistrol** [comment]
This is actually on purpose since the percentage in the Time Machine Settings only indicates the copying process. The percentage in TimeMachineStatus includes all states of the backup process (including "Starting", "Preparing", "Finishing", "Thinning", etc.)
