### ISSUE TITLE
🐞: [BUG] App opens settings window

### ISSUE THREAD

**Issue by gvmelle** [lukepistrol/TimeMachineStatus#34]
Every time I start the app it opens the settings window instead of just only the menubar icon.

 
![Screenshot 2024-09-19 at 14 26 24](https://github.com/user-attachments/assets/280ffa38-4623-448f-8ab2-a294e2861064)

Does it know if '**Full Disk access**' is already set???

**Comment by F1248** [comment]
I'm experiencing the same bug: Since upgrading to macOS Sequoia, the settings menu appears after every login (Launch at Login enabled):
- TimeMachineStatus 0.1.2 (16)
- macOS Sequoia 15.0 (24A335)
- MacBook Air M1 (MacBookAir10,1)

**Comment by gvmelle** [comment]
did not change in version 0.1.3.(17) still putting the icon in the menubar AND opening the settings window.

**Comment by lukepistrol** [comment]
This unfortunately is an issue that was introduced with macOS Sequoia and is not easily fixable with the current architecture of the app. 

I hope I’ll find some time to rework this soon.

**Comment by lukepistrol** [comment]
This should no longer be the case
