### ISSUE TITLE
🐞: [BUG] - application is not supported on this Mac.

### ISSUE THREAD

**Issue by grann0s** [lukepistrol/TimeMachineStatus#36]
When trying to run the latest version [ 0.2.1 ] of TimeMachineStatus on my iMac running macOS 15.1 [ Intel ] Finder reports the following error message :

"You can’t open the application “TimeMachineStatus” because this application is not supported on this Mac."

Attempting to execute the binary from the command line reports the following error message:

-bash: ./TimeMachineStatus: Bad CPU type in executable

**Comment by lukepistrol** [comment]
Interesting... 🤔 Did an earlier version work?

**Comment by grann0s** [comment]
Hi. The previous version worked but suffered from the same issue described in 🐞: [BUG] App opens settings window #34

**Comment by lukepistrol** [comment]
Ok I'll have a look at it next week.

**Comment by lukepistrol** [comment]
Ok found the issue. Should be fixed in 0.2.2.
