### ISSUE TITLE
🐞: [BUG]New App 0.2.1 not reconize by MacosX 15.0.1 (24A348)

### ISSUE THREAD

**Issue by EricM1967** [lukepistrol/TimeMachineStatus#38]
![Capture d’écran 2024-10-05 à 09 33 02](https://github.com/user-attachments/assets/3ff1a64b-174c-45e4-83ff-226aa7cec8c9)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lukepistrol** [comment]
What Mac are you using? Intel or Apple Silicon?

**Comment by lukepistrol** [comment]
If this was on an Intel Mac? this should be fixed in version 0.2.2.

**Comment by EricM1967** [comment]
Hello Lukas,

I use a Mac with an Intel processor.

Thank's

Eric
