### ISSUE TITLE
🐞: [BUG] App crash while backing-up and unable to open app

### ISSUE THREAD

**Issue by ghost** [lukepistrol/TimeMachineStatus#40]
**Describe the bug**
The application crash after few minutes, after have initiated a backup. (cf. "TimeMachineStatus_While_Backup")
Still while the backup is in progress, the application crash immediately at the opening. (cf. "TimeMachineStatus_Reopening_App.txt")

**To Reproduce**
1. Open "System Settings" > General > Time Machine > Right Click on volume > Back Up to ...

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
Operating System:
- Sequoia 15.0.1 - 24A348

Time Machine configuration:
- Backup Frequency: "Automatically Every Week"
- Back up on battery power: No
- Number of back up disks: 1
- Way of back up: Network Drive (SMB)

[TimeMachineStatus_While_Backup.txt](https://github.com/user-attachments/files/17416469/TimeMachineStatus_While_Backup.txt)
[TimeMachineStatus_Reopening_App.txt](https://github.com/user-attachments/files/17416470/TimeMachineStatus_Reopening_App.txt)

**Comment by lukepistrol** [comment]
Please open your Terminal.app and type in the following command to save the logs to a file on your Desktop. Ideally right after you restarted the app. Make sure to change the time stamp to before the error occurred.

```bash
log show --predicate 'sender == "TimeMachineStatus"' --start '2024-10-18 00:05:00' > ~/Desktop/TMS.log
```

Then please attach the file here.
